AllCops:
    TargetRubyVersion: 2.3

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 100
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
  EnforcedStyle: semantic
