# Themes
import = ["~/.config/alacritty/themes/gruvbox.toml"]
# import = ["~/.config/alacritty/themes/tokio-night.toml"]
# import = ["~/.config/alacritty/themes/everforest.toml"]

[env]
TERM = "xterm-256color"

# [shell]
# program = "zellij"

[window]
dimensions.columns = 150
dimensions.lines = 40
decorations = "Full"
padding.x = 0
padding.y = 0
dynamic_padding = true
opacity = 0.90
blur = true
option_as_alt = "Both"

[font]
size = 15.0
# normal = { family = "Menlo", style = "Regular" }
# bold = { family = "Menlo", style = "Bold" }
# italic = { family = "Menlo", style = "Italic" }
normal = { family = "MesloLGLDZ Nerd Font", style = "Regular" }
bold = { family = "MesloLGLDZ Nerd Font", style = "Bold" }
italic = { family = "MesloLGLDZ Nerd Font", style = "Italic" }

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "ArrowLeft", mods = "Command", chars = "\u001BB" },
  { key = "ArrowRight", mods = "Command", chars = "\u001BF" },
]

[[hints.enabled]]
regex = "[^ ]+\\.rb:\\d+:\\d+"
command = { program = "code", args = ["--goto"] }
mouse = { enabled = true }
